In [2]:
import numpy as np

In [48]:
a = np.array([[1,6],
              [2,8],
              [3,11],
              [3,10],
              [1,7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [49]:
mean_a = np.mean(a, axis = 0)
mean_a

array([2. , 8.4])

In [50]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [55]:
a_centered_sp = np.dot(a_centered[:,0],a_centered[:,1])
a_centered_sp 

8.0

In [59]:
N = a.shape[0]
N
cov_1 = a_centered_sp/(N-1)
cov_1

2.0

In [62]:
cov_2 = np.cov(a.T)
cov_2

array([[1. , 2. ],
       [2. , 4.3]])